feat: Preparing tests

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -34,6 +34,15 @@ jobs:
           distribution: 'corretto'
           java-version: '21'
 
+      - name: Verificar se existem testes e rodar cobertura
+        run: |
+          if ! find src/test/java -name "*Test.java" | grep -q .; then
+            echo "Nenhum teste encontrado. Abortando pipeline."
+            exit 1
+          fi
+          
+          mvn -B clean verify
+
       - name: Construir e testar
         run: mvn clean install
 
